// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamUp.Api.Data;

#nullable disable

namespace TeamUp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamUp.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Disliked")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("disliked");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FavoriteCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("favorite_category");

                    b.PrimitiveCollection<List<string>>("FavoriteGames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("favorite_games");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.PrimitiveCollection<List<string>>("Liked")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("liked");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("photo_url");

                    b.Property<int?>("PreferenceAgeMax")
                        .HasColumnType("integer")
                        .HasColumnName("preference_age_max");

                    b.Property<int?>("PreferenceAgeMin")
                        .HasColumnType("integer")
                        .HasColumnName("preference_age_min");

                    b.PrimitiveCollection<List<string>>("PreferenceCategories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preference_categories");

                    b.Property<string>("PreferenceGender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preference_gender");

                    b.PrimitiveCollection<List<string>>("PreferenceLanguages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preference_languages");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
